version: '2'
services:
 mysqldb:
  build: ../sysop-mysql
  container_name: mysql
  image: mcsaky/sysop-mysql
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=testpassword
   - MYSQL_DBNAME=test
   - MYSQL_DBPASS=test
   - MYSQL_DBUSER=test
   - CREATE_DATABASE=true
  cpu_shares: 50
  cpuset: 0,1
  mem_limit: 1024m
